theme = "shocky"

[editor]
color-modes = true
line-number = "relative"
mouse = false
rulers = [88]
shell = ["zsh", "-c"]
auto-format = true
bufferline = "multiple"
end-of-line-diagnostics = "disable" # "error"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable" # "error"

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
F5 = ":config-reload"
n = ["search_next", "align_view_center"]
N = ["search_prev", "align_view_center"]

C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]

"}" = ["goto_next_paragraph"]
"{" = ["goto_prev_paragraph"]

C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"
C-t = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80%"

[keys.normal.g]
x = ":bc"

[keys.normal.space]
C = "file_picker_in_current_buffer_directory" 
W = [":toggle soft-wrap.enable", ":redraw"]
z = ":pipe-to wezterm cli split-pane -- helix-live-zi"
q = ":quit-all"
Y = '@"%P"+d'

[keys.normal.space.o]
n = ":pipe-to wezterm cli split-pane -- helix-live-ob-name"
t = ":pipe-to wezterm cli split-pane -- helix-live-ob-tag"

[keys.normal.";"]
b = ":sh helix-wezterm blame"
e = ":sh helix-wezterm explorer"
f = ":pipe-to wezterm cli split-pane -- helix-live-grep"
g = ":sh helix-wezterm lazygit"
o = ":sh helix-wezterm open"
p = ":sh echo $(PWD)"
r = ":sh helix-wezterm run"
R = ":sh helix-wezterm run_debug"
s = ":sh helix-wezterm test_single"
t = ":sh helix-wezterm test_all"

[keys.select."]"]
"]" = "goto_next_paragraph"

[keys.select."["]
"[" = "goto_prev_paragraph"

